language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t myfirsttravis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true myfirsttravis/docker-react npm run test -- --coverage